### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by CharlesReinhardt** [snail-language/snail-language.github.io#10]
On the [documentation page,](https://snail-language.github.io/docs/getting-started#:~:text=Go%20to%20the-,Downloads,-page%20to%20obtain) the in text link to the downloads section results in "404 page not found" error. 

Currently, the link routes to `https://snail-language.github.io/download`

Other working links route to `https://snail-language.github.io/downloads`

**Comment by kevinaangstadt** [comment]
Fixed
