### ISSUE TITLE
Extra braces around blocks

### ISSUE THREAD

**Issue by kevinaangstadt** [snail-language/snail-language.github.io#3]
Originally reported by @dornja:

The [syntax specification](https://snail-language.github.io/docs/specification#snail-syntax) requires a pair of braces around every `block` in the `feature` and `expr` productions (except `expr ::= block`). But it also requires a pair of braces in the `block` production itself, which would result in double braces in most cases. This is inconsistent with the behavior of the reference implementation.

**Comment by kevinaangstadt** [comment]
@dornja I believe the latest update to the site fixes this concern.  Can you check that you agree?

**Comment by dornja** [comment]
Yes, looks good to me.
