### ISSUE TITLE
Typos in "new object" semantics

### ISSUE THREAD

**Issue by dornja** [snail-language/snail-language.github.io#6]
The semantic rules `New` and `New-Array` contain some typos.

This line of the `New` rule,
```
v, E', S' &\vdash \left\{ a_1 = e_1; \cdots; a_n = e_n \right\} : v_1, E_2, S_2
```
should probably read,
```
v_1, E_1, S_1 &\vdash \left\{ a_1 = e_1; \cdots; a_n = e_n \right\} : v, E_2, S_2
```
That is, the self object, environment and state should each have subscript `1` to match the definitions on the previous three lines, and the value _v_ that results from evaluating the block is not the result of the `new` expression. Instead, the self object _v_<sub>1</sub> is.

The definition of environment _E_<sub>1</sub> is currently missing curly braces. So,
```
E_1 &= {a_1 : l_1, \ldots, a_n : l_n}
```
should read,
```
E_1 &= \{a_1 : l_1, \ldots, a_n : l_n\}
```
In fact I might go so far as to say it should read
```
E_1 &= \{a_1 : l_1\}[l_2/a_2][l_3/a_3] \cdots [l_n/a_n]
```
or
```
E_1 &= \{\}[l_1/a_1] \cdots [l_n/a_n]
```
because the _a<sub>i</sub>_ are not guaranteed to be unique, and the `\{...\}` syntax doesn't specify what to do when two keys are the same. But I also acknowledge that may be more pedantic than is pedagogically valuable.

Finally, the conclusion of the `New-Array` rule ignores _v_ from the last precondition and instead introduces new names _l_ and _arr_ in the result:
```
so,E,S \vdash new[e_1]\; Array : Array(l, arr), E_1, S_1
```
could become
```
so,E,S \vdash new[e_1]\; Array : v, E_1, S_1
```

**Comment by kevinaangstadt** [comment]
In theory, I have corrected the typos in the `new` semantic rules.  There was also a mistake in that each initializer was not evaluated in its own local scope.  The updated opsems should also correct this.

I will return to the notation for constructing an environment after addressing an open issue in the reference interpreter dealing with duplicate members.
